# Generated by Django 3.2.8 on 2022-07-15 08:52

from django.db import migrations, models
import potholes.models


class Migration(migrations.Migration):

    dependencies = [
        ('potholes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='picture',
            field=models.ImageField(default='potholes/defaults.png', upload_to=potholes.models.upload_to, verbose_name='Image'),
        ),
    ]
