# Generated by Django 3.2.8 on 2022-07-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potholes', '0002_pothole_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pothole',
            old_name='adminarea',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='pothole',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
