# Generated by Django 3.2.8 on 2022-07-08 12:29

from django.db import migrations, models
import pothole.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='posts/default.jpg', upload_to=pothole.models.upload_to, verbose_name='Image')),
            ],
        ),
    ]
