# Generated by Django 3.2.8 on 2022-07-09 15:15

from django.db import migrations, models
import driver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='posts/default.jpg', upload_to=driver.models.upload_to, verbose_name='Image')),
                ('db', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('licenseno', models.CharField(max_length=100)),
            ],
        ),
    ]
