# Generated by Django 3.2.8 on 2022-07-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='db',
            field=models.DateField(max_length=40),
        ),
    ]
